### ISSUE TITLE
Filter by block type

### ISSUE THREAD

**Issue by judebert** [TheMrEngMan/SaveBlockStats#1]
This looks like a pretty clever solution to a basic data auditing problem. I'm not familiar enough with the Minecraft API to know for sure, so I'm guessing here: will this count "breaking blocks" like grass, flowers, and leaves? Will it count "placing blocks" like signs and fences?

It might be nice to have a config setting that included or excluded particular block types.

**Comment by TheMrEngMan** [comment]
Yes, any BlockPlaceEvent and BlockBreakEvent that are not cancelled by other plugins (e.g. trying to place a block in a WorldGuard region with no building permissions) gets counted. This includes everything you mentioned as well as using flint and steel to place fire and probably a few more things.

I agree, a feature to filter out certain blocks / only include certain blocks would be great to have and I'll probably implement it when I get the time.
(I just didn't need it for my use case so wanted to keep this as simple as possible initially)

**Comment by TheMrEngMan** [comment]
Added in [release 1.1](https://github.com/TheMrEngMan/SaveBlockStats/releases/tag/1.1)
